name: "Mydra"
on:
  push:
    branches:
      - master
  schedule:
    # Run each dat at 00,06,12 and 18 hours.
    - cron: '0 00,06,12,18 * * *'

jobs:
  Mydra:
    runs-on: ubuntu-20.04
    timeout-minutes: 65
    steps:

    # Installation
    - uses: actions/checkout@v2.3.4
    - uses: textbook/git-checkout-submodule-action@master
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - uses: cachix/cachix-action@v8
      with:
        name: rmcgibbo-mydra
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Run mydra
      env:
        AWS_BUCKET_CACHE: "s3://rmcgibbo-mydra-cache"
        AWS_BUCKET_LOGS: "s3://rmcgibbo-mydra-build-logs"
      run: |
        # Sync down build-{hash}.json files and mydra-failures.json
        # We really only need mydra-failures.json now, the other ones are used for the
        # mydra-generate step.
        mkdir ~/.cache/mydra
        nix run nixpkgs.awscli2 -c aws s3 sync --quiet $AWS_BUCKET_CACHE ~/.cache/mydra/

        ls ~/.cache/mydra  # Initial
        git clone https://github.com/NixOS/nixpkgs.git --branch master --single-branch nixpkgs  --depth 1 --quiet
        nix build -f .
        nix run -c mydra -f ./nixpkgs mydra.yml -t 60m
        nix run -c mydra-generate

        ls ~/.cache/mydra  # Final
        cat ~/.cache/mydra/mydra-failures.json

        # Upload new build logs
        nix run nixpkgs.awscli2 -c aws s3 sync --quiet ~/.cache/mydra-logs/ $AWS_BUCKET_LOGS

    # Deploy
    - name: Deploy GH pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        destination_dir: ./

