name: "Mydra"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: git clone --depth 1 git@github.com:NixOS/nixpkgs.git --branch master --single-branch nixpkgs
    - run: nix run -c mydra -f ./nixpkgs mydra.yml
