name: "Mydra"
on:
  pull_request:
  push:
jobs:
  Mydra:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: (cd /tmp && wget https://github.com/NixOS/nixpkgs/archive/master.tar.gz  -O - | tar -xz)
    - run: nix run -c mydra -f /tmp/nixpkgs-master mydra.yml
