name: "Mydra"
on:
  push:
    branches:
      - master
  schedule:
    # Run each dat at 00,06,12 and 18 hours.
    - cron: '0 00,06,12,18 * * *'

jobs:
  Mydra:
    runs-on: ubuntu-20.04
    timeout-minutes: 65
    steps:

    # Installation
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - uses: cachix/cachix-action@v8
      with:
        name: rmcgibbo-mydra
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install
      run: |
        mkdir -p ~/.cache/mydra
        nix-env --quiet -f '<nixpkgs>' -iA curl jq awscli2
        nix-env --quiet -f . -i

    - name: Run mydra
      env:
        AWS_BUCKET_CACHE: "s3://rmcgibbo-mydra-cache"
        AWS_BUCKET_LOGS: "s3://rmcgibbo-mydra-build-logs"
      run: |
        GITHUB_JOBRUN_ID=$(curl -sS "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs" | jq .jobs[0].id)
        GITHUB_JOBURL_URL="https://github.com/$GITHUB_REPOSITORY/runs/$GITHUB_JOBRUN_ID"

        # Sync down build-{hash}.json files and mydra-failures.json
        # We really only need mydra-failures.json now, the other ones are used for the
        # mydra-generate step.
        aws s3 sync --quiet $AWS_BUCKET_CACHE ~/.cache/mydra/

        git clone https://github.com/NixOS/nixpkgs.git --branch master --single-branch nixpkgs  --depth 1 --quiet
        mydra -f ./nixpkgs mydra.yml -t 60m --log-url $GITHUB_JOBURL_URL
        mydra-generate

        # Upload new build logs
        aws s3 sync --quiet --content-type text/plain ~/.cache/mydra-logs/ $AWS_BUCKET_LOGS

    # Deploy
    - name: Deploy GH pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        destination_dir: ./

