name: "Mydra"
on:
  pull_request:
  push:
jobs:
  Mydra:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: wget -qO- https://codeload.github.com/NixOS/nixpkgs/tar.gz/master | tar -xz
    - run: nix run -c mydra -f ./nixpkgs-master mydra.yml
