name: "Mydra"
on:
  pull_request:
  push:
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - run: git clone --depth 1 https://github.com/NixOS/nixpkgs.git --branch master --single-branch /tmp/nixpkgs
  Run:
    runs-on: ubuntu-latest
    needs: [Setup]
    steps:
    - run: nix run -c mydra -f /tmp/nixpkgs mydra.yml
